### ISSUE TITLE
NullPointerException When SELECT from JDBC DataSource.

### ISSUE THREAD

**Issue by wswuai** [qubole/Hive-JDBC-Storage-Handler#17]
I'm using this component with these below, i can insert data to hive external table with jdbc storagehandler, but when i try to select things from external table, i got nullpointer exception.

HDFS	2.6.0.2.2	

YARN	2.6.0.2.2

Tez	0.5.2.2.2	

Hive	0.14.0.2.2	

2016-01-14 15:59:33,118 ERROR [main]: CliDriver (SessionState.java:printError(834)) - Failed with exception java.io.IOException:java.lang.NullPointerException
java.io.IOException: java.lang.NullPointerException
        at org.apache.hadoop.hive.ql.exec.FetchOperator.getNextRow(FetchOperator.java:665)
        at org.apache.hadoop.hive.ql.exec.FetchOperator.pushRow(FetchOperator.java:563)
        at org.apache.hadoop.hive.ql.exec.FetchTask.fetch(FetchTask.java:140)
        at org.apache.hadoop.hive.ql.Driver.getResults(Driver.java:1647)
        at org.apache.hadoop.hive.cli.CliDriver.processLocalCmd(CliDriver.java:270)
        at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:202)
        at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:413)
        at org.apache.hadoop.hive.cli.CliDriver.executeDriver(CliDriver.java:786)
        at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:680)
        at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:619)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Caused by: java.lang.NullPointerException
        at org.apache.hadoop.mapreduce.TaskID$CharTaskTypeMaps.getRepresentingCharacter(TaskID.java:288)
        at org.apache.hadoop.mapreduce.TaskID.appendTo(TaskID.java:176)
        at org.apache.hadoop.mapreduce.TaskAttemptID.appendTo(TaskAttemptID.java:133)
        at org.apache.hadoop.mapreduce.TaskAttemptID.toString(TaskAttemptID.java:165)
        at org.apache.hadoop.hive.wrapper.RecordReaderWrapper.<init>(RecordReaderWrapper.java:114)
        at org.apache.hadoop.hive.wrapper.InputFormatWrapper.getRecordReader(InputFormatWrapper.java:60)
        at org.apache.hadoop.hive.jdbc.storagehandler.JdbcInputFormat.getRecordReader(JdbcInputFormat.java:55)
        at org.apache.hadoop.hive.ql.exec.FetchOperator.getRecordReader(FetchOperator.java:500)
        at org.apache.hadoop.hive.ql.exec.FetchOperator.getNextRow(FetchOperator.java:590)
        ... 15 more

**Comment by hava101** [comment]
@wswuai Thanks reporting this to us. Seems to be TaskType is not defined here. Will look further and get back to you shortly.

**Comment by wswuai** [comment]
I remove 64~65 , 111~114  in RecordReaderWrapper.java which related to taskAttemptID , the "mapred.task.id" might be removed from hadoop2. 

after that, it works.

**Comment by hava101** [comment]
Hey @wswuai , Sorry for the delay. 

Here is the PR: https://github.com/qubole/Hive-JDBC-Storage-Handler/pull/18

Please take a look and let me know, if the fix looks good.

**Comment by hava101** [comment]
@wswuai I have merged the PR. Thanks for reporting this to us.
