### ISSUE TITLE
NullPointerException at JdbcSerDe.deserialize

### ISSUE THREAD

**Issue by jeesim2** [qubole/Hive-JDBC-Storage-Handler#19]
Hi.

I have some problem to copy data from jdbc_hive_table to hive_table.

This is the full scenario.
```
==overview=====================================
MYSQL table <--[external]-- HiveTable -- [copy] --> HiveORC
==============================================
```

#### create table on mysql
```
CREATE TABLE `tb_mysql` (
   `id` varchar(100) NOT NULL,
   PRIMARY KEY (`id`)
) 
```

#### create jdbc external table on hive
```
CREATE EXTERNAL TABLE tb_mysql_jdbc (
  id STRING
)
STORED BY 'org.apache.hadoop.hive.jdbc.storagehandler.JdbcStorageHandler'
TBLPROPERTIES (
  "mapred.jdbc.driver.class"="com.mysql.jdbc.Driver",
  "mapred.jdbc.url"="jdbc:mysql://...",
  "mapred.jdbc.username"="",
  "mapred.jdbc.password"="",
  "mapred.jdbc.input.table.name"="tb_mysql",
  "mapred.jdbc.output.table.name" = "tb_mysql",
  "mapred.jdbc.hive.lazy.split"= "false"
);
```

#### create orc table on hive
```
CREATE TABLE `tb_orc`(
  `id` string)
    ROW FORMAT SERDE
      'org.apache.hadoop.hive.ql.io.orc.OrcSerde'
    STORED AS INPUTFORMAT
      'org.apache.hadoop.hive.ql.io.orc.OrcInputFormat'
    OUTPUTFORMAT
      'org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat'
```

#### then copy from tb_mysql_jdbc  to tb_orc
```
insert into tb_orcselect * from tb_mysql_jdbc  

at org.apache.hadoop.hive.ql.exec.tez.TezProcessor.initializeAndRunProcessor(TezProcessor.java:150) ... 14 more Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing writable null at org.apache.hadoop.hive.ql.exec.MapOperator.process(MapOperator.java:560
 at org.apache.hadoop.hive.ql.exec.tez.MapRecordSource.processRow(MapRecordSource.java:83) ... 17 more Caused by: java.lang.NullPointerException at org.apache.hadoop.hive.jdbc.storagehandler.JdbcSerDe.deserialize(JdbcSerDe.java:152
 at org.apache.hadoop.hive.ql.exec.MapOperator$MapOpCtx.readRow(MapOperator.java:146
 at org.apache.hadoop.hive.ql.exec.MapOperator$MapOpCtx.access$200(MapOperator.java:110
 at org.apache.hadoop.hive.ql.exec.MapOperator.process(MapOperator.java:551) ... 18 more ]], Vertex did not succeed due to OWN_TASK_FAILURE, failedTasks:1 killedTasks:0, Vertex vertex_1467878636123_1323_8_00 [Map 1] killed/failed due to:OWN_TASK_FAILURE]DAG did not succeed due to VERTEX_FAILURE. failedVertices:1 killedVertices:0
```

Is this not possible by this StorageHandler?

* application version
  * hive 1.3
  * tez 0.8

**Comment by changzong** [comment]
Are you using Tez engine for Hive? I encountered similar error while querying Hive table for MySQL data. But when I switched the execution engine to MapReduce, I can successfully fetch results from queries. Seems this StorageHandler doesn't support Tez yet.
