### ISSUE TITLE
mysql tinyint(1) type convert hive tinyint  java.lang.ClassCastException

### ISSUE THREAD

**Issue by sjywying** [qubole/Hive-JDBC-Storage-Handler#22]
2016-12-14 19:40:03,727 INFO  [main]: storagehandler.JdbcSerDe (JdbcSerDeHelper.java:setFilters(174)) - FilterPushDown Conditions: null
2016-12-14 19:40:03,729 INFO  [main]: storagehandler.JdbcDBInputFormat (JdbcDBInputFormat.java:createRecordReader(117)) - DB Type >> MYSQL
2016-12-14 19:40:03,730 ERROR [main]: CliDriver (SessionState.java:printError(960)) - Failed with exception java.io.IOException:org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Byte
java.io.IOException: org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Byte
	at org.apache.hadoop.hive.ql.exec.FetchTask.fetch(FetchTask.java:154)
	at org.apache.hadoop.hive.ql.Driver.getResults(Driver.java:1670)
	at org.apache.hadoop.hive.cli.CliDriver.processLocalCmd(CliDriver.java:233)
	at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:165)
	at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:376)
	at org.apache.hadoop.hive.cli.CliDriver.executeDriver(CliDriver.java:736)
	at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:681)
	at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:621)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Byte
	at org.apache.hadoop.hive.ql.exec.ListSinkOperator.process(ListSinkOperator.java:93)
	at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:837)
	at org.apache.hadoop.hive.ql.exec.SelectOperator.process(SelectOperator.java:88)
	at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:837)
	at org.apache.hadoop.hive.ql.exec.TableScanOperator.process(TableScanOperator.java:97)
	at org.apache.hadoop.hive.ql.exec.FetchOperator.pushRow(FetchOperator.java:424)
	at org.apache.hadoop.hive.ql.exec.FetchOperator.pushRow(FetchOperator.java:416)
	at org.apache.hadoop.hive.ql.exec.FetchTask.fetch(FetchTask.java:140)
	... 13 more
Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Byte
	at org.apache.hadoop.hive.serde2.objectinspector.primitive.JavaByteObjectInspector.get(JavaByteObjectInspector.java:40)
	at org.apache.hadoop.hive.serde2.lazy.LazyUtils.writePrimitiveUTF8(LazyUtils.java:194)
	at org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe.serialize(LazySimpleSerDe.java:307)
	at org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe.serializeField(LazySimpleSerDe.java:262)
	at org.apache.hadoop.hive.serde2.DelimitedJSONSerDe.serializeField(DelimitedJSONSerDe.java:72)
	at org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe.doSerialize(LazySimpleSerDe.java:246)
	at org.apache.hadoop.hive.serde2.AbstractEncodingAwareSerDe.serialize(AbstractEncodingAwareSerDe.java:50)
	at org.apache.hadoop.hive.ql.exec.DefaultFetchFormatter.convert(DefaultFetchFormatter.java:72)
	at org.apache.hadoop.hive.ql.exec.DefaultFetchFormatter.convert(DefaultFetchFormatter.java:40)
	at org.apache.hadoop.hive.ql.exec.ListSinkOperator.process(ListSinkOperator.java:90)
	... 20 more

**Comment by xuewang** [comment]
TINYINT(1) in MySQL represents a boolean value, try setting the field in hive to BOOLEAN.
