### ISSUE TITLE
Issue with the LIMIT Clause

### ISSUE THREAD

**Issue by danielhaviv** [qubole/Hive-JDBC-Storage-Handler#9]
I'm trying to use the storage handler with SQL Server but I fail as the LIMIT clause is being used (instead of the top clause in SQL server).
I tried fixing it in JdbcSerDeHelper.java but it seems to happen also somewhere else outside the code.

It would be nice if the Storage Handler would support both syntax (via a flag perhaps ?).

(If you could point me to where could be the other source of the LIMIT clause I would appreciate it).

Thank you.
Daniel

**Comment by hava101** [comment]
Hi Daniel, 
     Thanks for bringing this to our attention. We have raised a new PR with changes required to include support for SQL server as well. https://github.com/qubole/Hive-JDBC-Storage-Handler/pull/11
     Please take a look and let us know, if this solves ur problem. 

 Note: Please create a table by providing all the column details. 

Thanks, 
Pavan.

**Comment by danielhaviv** [comment]
Hi Pavan,
I tested the PR and it fails:
15/07/22 06:45:24 [main]: INFO Configuration.deprecation: mapred.input.dir is deprecated. Instead, use mapreduce.input.fileinputformat.inputdir
15/07/22 06:45:24 [main]: INFO storagehandler.JdbcSerDe: FilterPushDown Conditions: null
15/07/22 06:45:25 [main]: DEBUG storagehandler.JdbcSerDe: tblProps: {columns.types=int:string:double:double:double:double, location=hdfs://hdname.mycompany.com:8020/apps/hive/warehouse/db_jdbc.db/cmp_cost_jdbc_ext2, mapred.jdbc.username=-----, mapred.jdbc.url=jdbc:sqlserver://db.mycompany.com:1433;databaseName=mycompany, columns=campaign_id,cost_model,cost,ps,ad_spend_daily,ad_spend_total, serialization.format=1, serialization.ddl=struct cmp_cost_jdbc_ext2 { i32 campaign_id, string cost_model, double cost, double ps, double ad_spend_daily, double ad_spend_total}, transient_lastDdlTime=1437400387, columns.comments=from deserializerfrom deserializerfrom deserializerfrom deserializerfrom deserializerfrom deserializer, bucket_count=-1, file.outputformat=org.apache.hadoop.mapred.SequenceFileOutputFormat, serialization.lib=org.apache.hadoop.hive.jdbc.storagehandler.JdbcSerDe, mapred.jdbc.input.table.name=cmp_cost, mapred.jdbc.output.table.name=cmp_cost_jdbc_ext, storage_handler=org.apache.hadoop.hive.jdbc.storagehandler.JdbcStorageHandler, file.inputformat=org.apache.hadoop.mapred.SequenceFileInputFormat, EXTERNAL=TRUE, mapred.jdbc.password=mycompany321, mapred.jdbc.driver.class=com.microsoft.sqlserver.jdbc.SQLServerDriver, name=db_jdbc.cmp_cost_jdbc_ext2}
15/07/22 06:45:25 [main]: DEBUG storagehandler.JdbcSerDe: tblProps: {columns.types=int:string:double:double:double:double, location=hdfs://hdname.mycompany.com:8020/apps/hive/warehouse/db_jdbc.db/cmp_cost_jdbc_ext2, mapred.jdbc.username=-----, mapred.jdbc.url=jdbc:sqlserver://db.mycompany.com:1433;databaseName=mycompany, columns=campaign_id,cost_model,cost,ps,ad_spend_daily,ad_spend_total, serialization.format=1, serialization.ddl=struct cmp_cost_jdbc_ext2 { i32 campaign_id, string cost_model, double cost, double ps, double ad_spend_daily, double ad_spend_total}, transient_lastDdlTime=1437400387, columns.comments=from deserializerfrom deserializerfrom deserializerfrom deserializerfrom deserializerfrom deserializer, bucket_count=-1, file.outputformat=org.apache.hadoop.mapred.SequenceFileOutputFormat, serialization.lib=org.apache.hadoop.hive.jdbc.storagehandler.JdbcSerDe, mapred.jdbc.input.table.name=cmp_cost, mapred.jdbc.output.table.name=cmp_cost_jdbc_ext, storage_handler=org.apache.hadoop.hive.jdbc.storagehandler.JdbcStorageHandler, file.inputformat=org.apache.hadoop.mapred.SequenceFileInputFormat, EXTERNAL=TRUE, mapred.jdbc.password=mycompany321, mapred.jdbc.driver.class=com.microsoft.sqlserver.jdbc.SQLServerDriver, name=db_jdbc.cmp_cost_jdbc_ext2}
15/07/22 06:45:25 [main]: DEBUG exec.FetchOperator: Creating fetchTask with deserializer typeinfo: struct<campaign_id:int,cost_model:string,cost:double,ps:double,ad_spend_daily:double,ad_spend_total:double>
15/07/22 06:45:25 [main]: DEBUG exec.FetchOperator: deserializer properties:
table properties: {columns.types=int:string:double:double:double:double, location=hdfs://hdname.mycompany.com:8020/apps/hive/warehouse/db_jdbc.db/cmp_cost_jdbc_ext2, mapred.jdbc.username=-----, mapred.jdbc.url=jdbc:sqlserver://db.mycompany.com:1433;databaseName=mycompany, columns=campaign_id,cost_model,cost,ps,ad_spend_daily,ad_spend_total, serialization.format=1, serialization.ddl=struct cmp_cost_jdbc_ext2 { i32 campaign_id, string cost_model, double cost, double ps, double ad_spend_daily, double ad_spend_total}, transient_lastDdlTime=1437400387, columns.comments=from deserializerfrom deserializerfrom deserializerfrom deserializerfrom deserializerfrom deserializer, bucket_count=-1, file.outputformat=org.apache.hadoop.mapred.SequenceFileOutputFormat, serialization.lib=org.apache.hadoop.hive.jdbc.storagehandler.JdbcSerDe, mapred.jdbc.input.table.name=cmp_cost, storage_handler=org.apache.hadoop.hive.jdbc.storagehandler.JdbcStorageHandler, mapred.jdbc.output.table.name=cmp_cost_jdbc_ext, file.inputformat=org.apache.hadoop.mapred.SequenceFileInputFormat, mapred.jdbc.driver.class=com.microsoft.sqlserver.jdbc.SQLServerDriver, mapred.jdbc.password=mycompany321, EXTERNAL=TRUE, name=db_jdbc.cmp_cost_jdbc_ext2}
partition properties: {columns.types=int:string:double:double:double:double, location=hdfs://hdname.mycompany.com:8020/apps/hive/warehouse/db_jdbc.db/cmp_cost_jdbc_ext2, mapred.jdbc.username=-----, mapred.jdbc.url=jdbc:sqlserver://db.mycompany.com:1433;databaseName=mycompany, columns=campaign_id,cost_model,cost,ps,ad_spend_daily,ad_spend_total, serialization.format=1, serialization.ddl=struct cmp_cost_jdbc_ext2 { i32 campaign_id, string cost_model, double cost, double ps, double ad_spend_daily, double ad_spend_total}, transient_lastDdlTime=1437400387, columns.comments=from deserializerfrom deserializerfrom deserializerfrom deserializerfrom deserializerfrom deserializer, bucket_count=-1, file.outputformat=org.apache.hadoop.mapred.SequenceFileOutputFormat, serialization.lib=org.apache.hadoop.hive.jdbc.storagehandler.JdbcSerDe, mapred.jdbc.input.table.name=cmp_cost, storage_handler=org.apache.hadoop.hive.jdbc.storagehandler.JdbcStorageHandler, mapred.jdbc.output.table.name=cmp_cost_jdbc_ext, file.inputformat=org.apache.hadoop.mapred.SequenceFileInputFormat, mapred.jdbc.driver.class=com.microsoft.sqlserver.jdbc.SQLServerDriver, mapred.jdbc.password=mycompany321, EXTERNAL=TRUE, name=db_jdbc.cmp_cost_jdbc_ext2}
15/07/22 06:45:25 [main]: INFO storagehandler.JdbcSerDe: FilterPushDown Conditions: null
15/07/22 06:45:25 [main]: INFO Configuration.deprecation: mapred.task.id is deprecated. Instead, use mapreduce.task.attempt.id
Failed with exception java.io.IOException:java.io.IOException: SQLException in nextKeyValue
15/07/22 06:45:25 [main]: ERROR CliDriver: Failed with exception java.io.IOException:java.io.IOException: SQLException in nextKeyValue
java.io.IOException: java.io.IOException: SQLException in nextKeyValue
        at org.apache.hadoop.hive.ql.exec.FetchOperator.getNextRow(FetchOperator.java:663)
        at org.apache.hadoop.hive.ql.exec.FetchOperator.pushRow(FetchOperator.java:561)
        at org.apache.hadoop.hive.ql.exec.FetchTask.fetch(FetchTask.java:138)
        at org.apache.hadoop.hive.ql.Driver.getResults(Driver.java:1621)
        at org.apache.hadoop.hive.cli.CliDriver.processLocalCmd(CliDriver.java:267)
        at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:199)
        at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:410)
        at org.apache.hadoop.hive.cli.CliDriver.executeDriver(CliDriver.java:783)
        at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:677)
        at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:616)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Caused by: java.io.IOException: SQLException in nextKeyValue
        at org.apache.hadoop.mapreduce.lib.db.DBRecordReader.nextKeyValue(DBRecordReader.java:239)
        at org.apache.hadoop.hive.wrapper.RecordReaderWrapper.<init>(RecordReaderWrapper.java:86)
        at org.apache.hadoop.hive.wrapper.InputFormatWrapper.getRecordReader(InputFormatWrapper.java:59)
        at org.apache.hadoop.hive.jdbc.storagehandler.JdbcInputFormat.getRecordReader(JdbcInputFormat.java:71)
        at org.apache.hadoop.hive.ql.exec.FetchOperator.getRecordReader(FetchOperator.java:498)
        at org.apache.hadoop.hive.ql.exec.FetchOperator.getNextRow(FetchOperator.java:588)
        ... 15 more
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near 'LIMIT'.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
        at org.apache.hadoop.mapreduce.lib.db.DBRecordReader.executeQuery(DBRecordReader.java:108)
        at org.apache.hadoop.mapreduce.lib.db.DBRecordReader.nextKeyValue(DBRecordReader.java:227)
        ... 20 more

**Comment by divyanshu25** [comment]
Hi Daniel.
We have updated the PR. Please check it.
Points to consider:
1. We have added MicrosoftDBRecordReader.java which is the file where query
to be executed on DB is generated. So if sql syntax error still persists
you can modify the code there.
2. JdbcDBInputFormat.java decides on basis of DBProductName which
DBRecorder to invoke. We believe SQL-server should return Microsoft Sql
server so please do check it.

Please let us know if you still have any problem

Regards
Divyanshu Goyal

**Comment by danielhaviv** [comment]
Hi Divyanshu,
Great work, there are still a few things to iron out:
1. The product name is all upper case so line 96 in JdbcDBInputFormat.java should change to:
            if((super.getDBProductName()).startsWith("MICROSOFT SQL SERVER") ){

2. After that I encountered a null pointer exception coming from getSelectQuery's try block in MicrosoftDBRecordReader.java so I changed the exception type to Exception in line 111.

3. Another thing I noticed is that if M/R is not involved (local mode execution), a connection is not being opened so they query fails on "connection is closed".

4. Another problem I'm facing, which I'm not sure is a bug with Hive or related to the JDBC Storage Handler, is that when I define a field in my hive table as Decimal I'm getting the following exception:
Caused by: java.lang.RuntimeException: MetaException(message:org.apache.hadoop.hive.serde2.SerDeException Unrecognized column type: decimal(10,0))
        at org.apache.hadoop.hive.ql.metadata.Table.getDeserializerFromMetaStore(Table.java:265)
        at org.apache.hadoop.hive.ql.metadata.Table.getDeserializer(Table.java:256)
        at org.apache.hadoop.hive.ql.metadata.Table.getCols(Table.java:610)
        at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:651)
        ... 21 more
Caused by: MetaException(message:org.apache.hadoop.hive.serde2.SerDeException Unrecognized column type: decimal(10,0))
        at org.apache.hadoop.hive.metastore.MetaStoreUtils.getDeserializer(MetaStoreUtils.java:375)
        at org.apache.hadoop.hive.ql.metadata.Table.getDeserializerFromMetaStore(Table.java:263)
        ... 24 more

Other than that, after fixing sections 1 to 3, if I query just a table of strings it works :)

Thank you.

**Comment by divyanshu25** [comment]
Hey Daniel,
Cool, Good to hear it worked for you. Thanks for pointing out the bugs.
Will fix them in next PR. :)

**Comment by divyanshu25** [comment]
Hey daniel,
for resolving the second point you mentioned.
please do
*set mapred.map.tasks = 1;   *
 on hive command line prompt.
Please let me know if that fixes the problem.

**Comment by danielhaviv** [comment]
Hi Divyanshu,
It works when M/R is involved.

Thank you.
Daniel

**Comment by divyanshu25** [comment]
Yeah that is fine . I was asking about scenario when no map reduce job is
initiated . Example select * from table . Does that also work fine for you ?

**Comment by danielhaviv** [comment]
Hi,
Yes it solves it even in local mode.

Daniel
